### ISSUE TITLE
Not working with XLD 6.x

### ISSUE THREAD

**Issue by brhahlen** [xebialabs-community/xld-versions-plugin#1]
This plugin unfortunately doesn't work anymore with XLD 6.x
Can this be updated for this 6.x?

**Comment by jdewinne** [comment]
And what is not working in 6.x? I've tried with 6.0.2 without any issues.

**Comment by brhahlen** [comment]
We are getting a blank screen and it's stuck at loading.

**Comment by brhahlen** [comment]
It was a temporary glitch. No issue anymore.
